/**
 * Default exercises library
 * These are the exercises from the original Dancer's Split plan
 */

import { Exercise, generateId } from "./workoutLibrary";

export function createDefaultExercises(): Exercise[] {
  return [
    // Day 1 - Lower Body Strength & Stability
    {
      id: generateId(),
      name: "Leg Press (Bilateral)",
      category: "strength",
      muscleGroups: ["legs", "quads", "glutes"],
      equipment: ["Leg Press Machine"],
      defaultRepRange: [6, 8],
      defaultSets: 4,
      defaultRestSec: 150, // 2-3 min = 150s average
    },
    {
      id: generateId(),
      name: "Bulgarian Split Squats",
      category: "strength",
      muscleGroups: ["legs", "quads", "glutes"],
      defaultRepRange: [8, 10],
      defaultSets: 3,
      defaultRestSec: 90,
    },
    {
      id: generateId(),
      name: "Romanian Deadlifts",
      category: "strength",
      muscleGroups: ["hamstrings", "glutes", "back"],
      defaultRepRange: [8, 10],
      defaultSets: 3,
      defaultRestSec: 90,
    },
    {
      id: generateId(),
      name: "Single-Leg Leg Curl",
      category: "strength",
      muscleGroups: ["hamstrings"],
      equipment: ["Leg Curl Machine"],
      defaultRepRange: [8, 10],
      defaultSets: 3,
      defaultRestSec: 60,
    },
    {
      id: generateId(),
      name: "Pallof Press",
      category: "strength",
      muscleGroups: ["core"],
      equipment: ["Cable Machine"],
      defaultRepRange: [10, 12],
      defaultSets: 3,
      defaultRestSec: 60,
    },
    {
      id: generateId(),
      name: "Deep Goblet Squat Hold (Kettlebell)",
      category: "strength",
      muscleGroups: ["legs", "core"],
      equipment: ["Kettlebell"],
      isTimed: true,
      defaultSeconds: 30,
      defaultSets: 3,
      defaultRestSec: 60,
    },
    {
      id: generateId(),
      name: "Standing Calf Raises",
      category: "strength",
      muscleGroups: ["calves"],
      defaultRepRange: [12, 15],
      defaultSets: 4,
      defaultRestSec: 45,
    },

    // Day 2 - Upper Body Strength & Posture
    {
      id: generateId(),
      name: "Lat Pulldown (Wide Grip)",
      category: "strength",
      muscleGroups: ["back"],
      equipment: ["Cable Machine"],
      defaultRepRange: [10, 12],
      defaultSets: 4,
      defaultRestSec: 150,
    },
    {
      id: generateId(),
      name: "Seated Row (Neutral Grip)",
      category: "strength",
      muscleGroups: ["back"],
      equipment: ["Cable Machine"],
      defaultRepRange: [12, 15],
      defaultSets: 3,
      defaultRestSec: 90,
    },
    {
      id: generateId(),
      name: "Smith Machine Overhead Press",
      category: "strength",
      muscleGroups: ["shoulders"],
      equipment: ["Smith Machine"],
      defaultRepRange: [6, 8],
      defaultSets: 3,
      defaultRestSec: 90,
    },
    {
      id: generateId(),
      name: "Incline Dumbbell Press",
      category: "strength",
      muscleGroups: ["chest", "shoulders"],
      equipment: ["Dumbbells"],
      defaultRepRange: [8, 10],
      defaultSets: 3,
      defaultRestSec: 90,
    },
    {
      id: generateId(),
      name: "Cable Face Pulls",
      category: "strength",
      muscleGroups: ["back", "shoulders"],
      equipment: ["Cable Machine"],
      defaultRepRange: [12, 15],
      defaultSets: 3,
      defaultRestSec: 60,
    },
    {
      id: generateId(),
      name: "Assisted Dips",
      category: "strength",
      muscleGroups: ["arms", "chest", "shoulders"],
      equipment: ["Dip Machine"],
      defaultSets: 3,
      defaultRestSec: 60,
      notes: "To failure",
    },
    {
      id: generateId(),
      name: "Suitcase Carry",
      category: "strength",
      muscleGroups: ["core", "back"],
      equipment: ["Kettlebell", "Dumbbell"],
      isTimed: true,
      defaultSeconds: 30,
      defaultSets: 2,
      defaultRestSec: 0, // No rest between sides
    },

    // Day 3 - Full-Body Power & Endurance (Circuit)
    {
      id: generateId(),
      name: "Kettlebell Swings",
      category: "strength",
      muscleGroups: ["full-body", "glutes"],
      equipment: ["Kettlebell"],
      isTimed: true,
      defaultSeconds: 45,
    },
    {
      id: generateId(),
      name: "Box Jumps",
      category: "plyometric",
      muscleGroups: ["legs", "glutes"],
      equipment: ["Box"],
      isTimed: true,
      defaultSeconds: 45,
    },
    {
      id: generateId(),
      name: "Broad Jumps",
      category: "plyometric",
      muscleGroups: ["legs", "glutes"],
      isTimed: true,
      defaultSeconds: 45,
    },
    {
      id: generateId(),
      name: "Push-Ups",
      category: "strength",
      muscleGroups: ["chest", "arms", "shoulders"],
      isTimed: true,
      defaultSeconds: 45,
    },
    {
      id: generateId(),
      name: "Single-Leg RDL (Bodyweight)",
      category: "strength",
      muscleGroups: ["hamstrings", "glutes"],
      isTimed: true,
      defaultSeconds: 45,
    },
    {
      id: generateId(),
      name: "Bird Dog Crunch",
      category: "core",
      muscleGroups: ["core"],
      defaultRepRange: [10, 12],
    },
    {
      id: generateId(),
      name: "Plank",
      category: "strength",
      muscleGroups: ["core"],
      isTimed: true,
      defaultSeconds: 60,
    },

    // Day 4 - Dance-Specific Power & Plyometrics
    {
      id: generateId(),
      name: "Depth Drops to Stick Landing",
      category: "dance-specific",
      muscleGroups: ["legs", "core"],
      defaultRepRange: [5, 5],
      defaultSets: 3,
      defaultRestSec: 150,
    },
    {
      id: generateId(),
      name: "Lateral Skater Jumps",
      category: "plyometric",
      muscleGroups: ["legs", "glutes"],
      defaultRepRange: [8, 8],
      defaultSets: 3,
      defaultRestSec: 90,
    },
    {
      id: generateId(),
      name: "Single-Leg Box Jumps",
      category: "dance-specific",
      muscleGroups: ["legs", "glutes"],
      equipment: ["Box"],
      defaultRepRange: [5, 5],
      defaultSets: 3,
      defaultRestSec: 90,
    },
    {
      id: generateId(),
      name: "Copenhagen Planks",
      category: "strength",
      muscleGroups: ["core"],
      defaultRepRange: [8, 10],
      defaultSets: 3,
      defaultRestSec: 60,
    },
    {
      id: generateId(),
      name: "Band-Resisted Ankle Jumps",
      category: "dance-specific",
      muscleGroups: ["calves", "legs"],
      equipment: ["Resistance Band"],
      defaultRepRange: [15, 15],
      defaultSets: 3,
      defaultRestSec: 60,
    },
  ];
}

